import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type {
  CatalogGenerationInput,
  CatalogGenerationOutput,
  DocsCatalogSource,
  GeneratedCatalogModule,
  PromptCatalogEntry,
  ResourceCatalogEntry,
  RuntimeDefaults,
  ServerOperationMetadata,
  ToolCatalogEntry
} from "../src/contracts.js";
import {
  PROMPT_CATALOG_SEED,
  RESOURCE_CATALOG_SEED,
  RUNTIME_DEFAULTS_TEMPLATE,
  TOOL_CATALOG_SEED
} from "../src/catalog-seed.js";

interface ProtocolManifestRecord {
  readonly sourceUrl: string;
  readonly localPath: string;
  readonly sha256: string;
  readonly downloadedAt: string;
}

interface ProtocolManifest {
  readonly generatedAt: string;
  readonly records: readonly ProtocolManifestRecord[];
}

const REPO_ROOT = path.resolve(process.cwd());
const MANIFEST_PATH = path.join(REPO_ROOT, "docs/protocol/manifest.json");
const GENERATED_DIR = path.join(REPO_ROOT, "src/generated");

export function toDocSlug(localPath: string): string {
  return localPath
    .replace(/\.md$/u, "")
    .replace(/[^a-zA-Z0-9]+/gu, "-")
    .replace(/^-+/u, "")
    .replace(/-+$/u, "")
    .toLowerCase();
}

export function buildDocsIndexEntries(manifest: ProtocolManifest): readonly DocsCatalogSource[] {
  return [...manifest.records]
    .sort((left, right) => left.localPath.localeCompare(right.localPath))
    .map((record) => ({
      slug: toDocSlug(record.localPath),
      localPath: record.localPath,
      sourceUrl: record.sourceUrl,
      generatedAt: manifest.generatedAt,
      sha256: record.sha256
    }));
}

export function buildCatalogGenerationInput(
  manifest: ProtocolManifest,
  runtimeDefaultsTemplate: RuntimeDefaults = RUNTIME_DEFAULTS_TEMPLATE
): CatalogGenerationInput {
  return {
    generatedAt: manifest.generatedAt,
    docs: buildDocsIndexEntries(manifest),
    tools: TOOL_CATALOG_SEED,
    resources: RESOURCE_CATALOG_SEED,
    prompts: PROMPT_CATALOG_SEED,
    runtimeDefaultsTemplate
  };
}

export function generateCatalogArtifacts(input: CatalogGenerationInput): CatalogGenerationOutput {
  const operationMetadata: readonly ServerOperationMetadata[] = input.tools.map((tool) => ({
    operationId: tool.operationId,
    minimumPermissionLevel: tool.minimumPermissionLevel,
    sensitivity: tool.sensitivity,
    supportsRuntimeDefaults: tool.supportsRuntimeDefaults,
    paginationMode: tool.paginationMode,
    docsAvailability: tool.docsAvailability
  }));

  const modules: readonly GeneratedCatalogModule[] = [
    {
      path: path.join(GENERATED_DIR, "catalog.generated.ts"),
      contents: renderCatalogModule(input.tools, input.resources, input.prompts)
    },
    {
      path: path.join(GENERATED_DIR, "runtime-contracts.generated.ts"),
      contents: renderRuntimeContractsModule(operationMetadata, input.runtimeDefaultsTemplate)
    },
    {
      path: path.join(GENERATED_DIR, "docs-index.generated.ts"),
      contents: renderDocsIndexModule(input.docs)
    }
  ];

  return {
    generatedAt: input.generatedAt,
    docs: input.docs,
    tools: input.tools,
    resources: input.resources,
    prompts: input.prompts,
    runtimeDefaultsTemplate: input.runtimeDefaultsTemplate,
    modules
  };
}

export async function writeGeneratedArtifacts(output: CatalogGenerationOutput): Promise<void> {
  await Promise.all(
    output.modules.map(async (module) => {
      await writeFile(module.path, module.contents, "utf8");
    })
  );
}

function renderCatalogModule(
  tools: readonly ToolCatalogEntry[],
  resources: readonly ResourceCatalogEntry[],
  prompts: readonly PromptCatalogEntry[]
): string {
  return [
    "/* This file is generated by tools/generate-catalog.ts. Do not edit manually. */",
    'import type { PromptCatalogEntry, ResourceCatalogEntry, ToolCatalogEntry } from "../contracts.js";',
    "",
    `export const TOOL_CATALOG: readonly ToolCatalogEntry[] = ${serializeConst(tools)};`,
    "",
    `export const RESOURCE_CATALOG: readonly ResourceCatalogEntry[] = ${serializeConst(resources)};`,
    "",
    `export const PROMPT_CATALOG: readonly PromptCatalogEntry[] = ${serializeConst(prompts)};`,
    ""
  ].join("\n");
}

function renderRuntimeContractsModule(
  operationMetadata: readonly ServerOperationMetadata[],
  runtimeDefaultsTemplate: RuntimeDefaults
): string {
  return [
    "/* This file is generated by tools/generate-catalog.ts. Do not edit manually. */",
    'import type { RuntimeDefaults, ServerOperationMetadata } from "../contracts.js";',
    "",
    `export const OPERATION_METADATA: readonly ServerOperationMetadata[] = ${serializeConst(operationMetadata)};`,
    "",
    `export const RUNTIME_DEFAULTS_TEMPLATE_GENERATED: Readonly<RuntimeDefaults> = ${serializeConst(runtimeDefaultsTemplate)};`,
    ""
  ].join("\n");
}

function renderDocsIndexModule(docs: readonly DocsCatalogSource[]): string {
  return [
    "/* This file is generated by tools/generate-catalog.ts. Do not edit manually. */",
    'import type { DocsCatalogSource } from "../contracts.js";',
    "",
    `export const DOCS_INDEX: readonly DocsCatalogSource[] = ${serializeConst(docs)};`,
    ""
  ].join("\n");
}

function serializeConst(value: unknown): string {
  return `${JSON.stringify(value, null, 2)} as const`;
}

async function readProtocolManifest(manifestPath: string): Promise<ProtocolManifest> {
  const raw = await readFile(manifestPath, "utf8");
  const parsed = JSON.parse(raw) as ProtocolManifest;
  return parsed;
}

async function main(): Promise<void> {
  const manifest = await readProtocolManifest(MANIFEST_PATH);
  const input = buildCatalogGenerationInput(manifest);
  const output = generateCatalogArtifacts(input);
  await writeGeneratedArtifacts(output);
  process.stdout.write(`Generated ${output.modules.length} catalog modules.\n`);
}

const isEntryPoint =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));
if (isEntryPoint) {
  void main();
}
